import type { MirrorConfig } from "@documirror/shared";

export function createDefaultConfig(
  siteUrl: string,
  targetLocale: string,
): MirrorConfig {
  return {
    sourceUrl: siteUrl,
    targetLocale,
    entryUrls: [siteUrl],
    includePatterns: [],
    excludePatterns: [],
    crawlConcurrency: 4,
    requestHeaders: {
      "user-agent": "DocuMirror/0.1.0",
    },
    selectors: {
      include: [],
      exclude: [
        "script",
        "style",
        "noscript",
        "pre",
        "code",
        ".language-switcher",
      ],
    },
    attributeRules: {
      translate: ["title", "alt", "aria-label", "placeholder"],
      ignore: ["data-*"],
    },
    build: {
      basePath: "/",
    },
  };
}

export function createTaskGuide(): string {
  return `# DocuMirror Translation Tasks

This folder contains translation task files generated by DocuMirror.

Workflow:
1. Read JSON files from .documirror/tasks/pending/
2. Translate each item.sourceText into the requested target language
3. Preserve placeholders, inline markup, and list numbering
4. Write result files into .documirror/tasks/done/

Result schema:
{
  "schemaVersion": 1,
  "taskId": "task_xxx",
  "provider": "claude-code",
  "completedAt": "2026-01-01T00:00:00.000Z",
  "items": [
    {
      "segmentId": "...",
      "sourceHash": "...",
      "translatedText": "..."
    }
  ]
}
`;
}

export function createMirrorRepoPackageJson(
  siteUrl: string,
  targetLocale: string,
): Record<string, unknown> {
  const sourceUrl = new URL(siteUrl);
  const repoName = createPackageName(sourceUrl.hostname, targetLocale);

  return {
    name: repoName,
    private: true,
    version: "0.1.0",
    description: `Translated mirror workspace for ${sourceUrl.origin} (${targetLocale})`,
    packageManager: "pnpm@10.22.0",
    engines: {
      node: ">=20",
    },
    scripts: {
      "documirror:crawl": "documirror crawl --repo .",
      "documirror:extract": "documirror extract --repo .",
      "documirror:translate:plan": "documirror translate plan --repo .",
      "documirror:translate:apply": "documirror translate apply --repo .",
      "documirror:build": "documirror build --repo .",
      "documirror:update": "documirror update --repo .",
      "documirror:doctor": "documirror doctor --repo .",
      "documirror:status": "documirror status --repo .",
    },
  };
}

export function createMirrorRepoReadme(
  siteUrl: string,
  targetLocale: string,
): string {
  return `# DocuMirror Mirror Repository

This repository stores the translated mirror workflow for:

- Source site: ${siteUrl}
- Target locale: ${targetLocale}

## Requirements

- Node.js >= 20
- pnpm >= 10
- A globally available \`documirror\` CLI

If you are developing DocuMirror locally, you can expose the CLI globally with:

\`\`\`bash
pnpm --filter @documirror/cli build
pnpm --filter @documirror/cli link --global
\`\`\`

## Repository Layout

- \`.documirror/config.json\`: mirror configuration
- \`.documirror/state/manifest.json\`: page and asset manifest
- \`.documirror/content/segments.jsonl\`: extracted source segments
- \`.documirror/content/translations.jsonl\`: accepted translations
- \`.documirror/tasks/pending/\`: translation tasks for external agents
- \`.documirror/tasks/done/\`: translation result files waiting to be applied
- \`site/\`: built translated static site output
- \`reports/\`: doctor and verification reports

## Common Commands

Update crawl state and generate translation tasks:

\`\`\`bash
pnpm documirror:update
\`\`\`

Run the steps separately:

\`\`\`bash
pnpm documirror:crawl
pnpm documirror:extract
pnpm documirror:translate:plan
\`\`\`

After an external AI agent writes result files into \`.documirror/tasks/done/\`, apply them:

\`\`\`bash
pnpm documirror:translate:apply
\`\`\`

Build the translated mirror:

\`\`\`bash
pnpm documirror:build
\`\`\`

Inspect repository state:

\`\`\`bash
pnpm documirror:status
pnpm documirror:doctor
\`\`\`

## Translation Workflow

1. Run \`pnpm documirror:update\`
2. Read task files from \`.documirror/tasks/pending/\`
3. Translate each task item with your preferred AI agent
4. Write result JSON files into \`.documirror/tasks/done/\`
5. Run \`pnpm documirror:translate:apply\`
6. Run \`pnpm documirror:build\`

For task and result JSON examples, see \`.documirror/TASKS.md\`.
`;
}

function createPackageName(hostname: string, targetLocale: string): string {
  const normalizedHost = hostname
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  const normalizedLocale = targetLocale
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

  return `documirror-mirror-${normalizedHost}-${normalizedLocale}`;
}
