export function createMirrorRepoAgents(
  siteUrl: string,
  targetLocale: string,
): string {
  return `# AGENTS.md

This file is the repository guide for contributors working in this DocuMirror mirror repository.

## Project Goal

This repository stores the translated mirror workflow for:

- Source site: ${siteUrl}
- Target locale: ${targetLocale}

The goal is to keep a repeatable static-site translation pipeline:

1. crawl the source documentation site
2. extract translatable HTML text and attributes
3. run automatic API translation for queued task files
4. apply accepted translations
5. build a deployable translated static mirror, with an opt-in runtime reconciler fallback for hydration-heavy pages

## Requirements

- Node.js >= 20
- pnpm >= 10
- A globally available \`documirror\` CLI

If you are developing DocuMirror locally, expose the CLI globally with:

\`\`\`bash
pnpm --filter @documirror/cli build
pnpm --filter @documirror/cli link --global
\`\`\`

## Repository Layout

- \`README.md\`: quick start for humans
- \`AGENTS.md\`: repository operating guide for agents and contributors
- \`.documirror/TASKS.md\`: translation task handling rules and result format
- \`site/\`: translated mirror output generated by the build step
- \`reports/\`: doctor and verification reports

## Working Files Under .documirror

- \`config.json\`: mirror configuration
- \`glossary.json\`: required source-to-target term mappings
- \`cache/pages/\`: fetched HTML snapshots
- \`cache/assets/\`: fetched static assets
- \`content/segments.jsonl\`: extracted source segments
- \`content/translations.jsonl\`: accepted translations
- \`state/manifest.json\`: crawled pages and assets manifest
- \`state/assembly.json\`: HTML assembly mapping used during build
- \`state/task-mappings/\`: mapping from task item ids back to internal segments
- \`tasks/pending/\`: generated task files waiting to be claimed
- \`tasks/done/\`: verified results waiting to be applied
- \`tasks/applied/\`: applied result history
- \`tasks/manifest.json\`: machine-readable task queue state
- \`tasks/QUEUE.md\`: generated checklist view of the queue
- \`.env\`: AI auth token for the configured model provider

## Standard Workflow

1. Run the preferred one-shot workflow:

\`\`\`bash
pnpm documirror:auto
\`\`\`

This runs \`update\`, \`translate run\`, \`translate apply\`, and \`build\` in order. If some translation tasks fail, it still applies successful results and builds the site, but exits non-zero.

2. Refresh source state manually when you need finer control:

\`\`\`bash
pnpm documirror:update
\`\`\`

3. Review the generated queue:

\`\`\`bash
cat .documirror/tasks/QUEUE.md
\`\`\`

4. Run automatic translation:

\`\`\`bash
pnpm documirror:translate:run
\`\`\`

When a \`pnpm documirror:*\` script needs extra CLI flags such as \`--task\`, keep the extra \`--\` so pnpm forwards those flags to the DocuMirror CLI.

5. Verify a generated result if you need to inspect it:

\`\`\`bash
pnpm documirror:translate:verify -- --task <taskId>
\`\`\`

6. Apply verified results and rebuild the site:

\`\`\`bash
pnpm documirror:translate:apply
pnpm documirror:build
\`\`\`

## Common Commands

\`\`\`bash
pnpm documirror:auto
pnpm documirror:update
pnpm documirror:crawl
pnpm documirror:extract
pnpm documirror:config:ai
pnpm documirror:translate:plan
pnpm documirror:translate:run
pnpm documirror:translate:verify -- --task <taskId>
pnpm documirror:translate:apply
pnpm documirror:build
pnpm documirror:status
pnpm documirror:doctor
\`\`\`

## Key Concepts

- \`segmentId\` is the stable internal identifier for an extracted page + DOM path + content kind binding.
- \`sourceHash\` is the normalized source-content hash used to decide whether an existing translation is still valid.
- External task files use short item ids such as \`1\`, \`2\`, and \`3\` for agent-friendly translation work.
- Internal state maps those short ids back to \`segmentId\` and \`sourceHash\` through files under \`state/task-mappings/\`.
- \`translate plan\` only exports work that is new, stale, or missing an accepted translation.
- \`translate run\` calls the configured OpenAI-compatible API directly. Large page tasks may be split into a few runtime chunks internally, but verified results are still written into \`tasks/done/\` as page-level files.
- \`translate apply\` rejects stale results whose source hash no longer matches the current extracted content.

## Guardrails

- Do not edit \`.documirror/tasks/manifest.json\` or \`.documirror/tasks/QUEUE.md\` by hand.
- Always check \`.documirror/glossary.json\` before translating.
- Keep \`.env\` private and never commit provider tokens.
- Preserve inline code, placeholders, list markers, markdown structure, and HTML entities.
- Do not move surrounding text across inline code boundaries.
- Run verify if you modify a result manually; do not bypass \`translate apply\`.
- Apply results through the CLI instead of editing \`translations.jsonl\` directly.
- Read \`.documirror/TASKS.md\` for the task result schema and translation-specific rules.

## Collaboration Rules

- Treat generated queue files and state files as the source of truth.
- Preserve existing repository files; if \`init\` is re-run, missing scaffold files may be added but existing text files should not be overwritten.
- Keep changes inspectable on disk and prefer the existing file-based workflow over ad hoc side channels.
- When in doubt about translation procedure, follow \`.documirror/TASKS.md\` first and this file second.
`;
}
