export function createTaskGuide(): string {
  return `# DocuMirror Translation Tasks

This folder contains translation task files generated by DocuMirror.

## Workflow

1. Read JSON files from \`.documirror/tasks/pending/\`
2. Translate each page task following the rules below
3. Write result files into \`.documirror/tasks/done/\`

## Translation Rules (MUST Follow)

### 1. Completeness - No Omission, No Addition
- Translate **ALL** content items. Do not skip any item.
- Each item has a unique \`id\`. Your result must include a translation for **every** id.
- Do NOT add extra content, explanations, or notes that were not in the source.
- Do NOT merge or split items. One source item → one translated item.

### 2. Glossary Consistency
- **ALWAYS** check \`.documirror/glossary.json\` before translating.
- If a source term exists in the glossary, you **MUST** use the specified translation.
- If you encounter a new technical term that should be standardized:
  1. Note it down
  2. After completing all tasks, suggest additions to \`glossary.json\`

### 3. Inline Code Preservation
- Text wrapped in backticks \`\` \`code\` \`\` is **inline code**.
- **NEVER** translate or modify inline code content.
- **PRESERVE** the exact backtick count, order, and position.
- Example: \`The \`foo\` function\` → \`\\u51fd\\u6570 \`foo\`\`

### 4. Formatting Preservation
- Preserve list numbering (1., 2., 3.)
- Preserve markdown formatting (**bold**, *italic*, [links])
- Preserve HTML entities and placeholders

### 5. Context Awareness
- Each item may include a \`note\` field for context (e.g., \`<img> @alt\`).
- Use the \`page.title\` and \`page.url\` to understand the document context.
- When an item contains unchanged neighboring text around inline code, translate only the translatable parts while keeping the inline code intact.

## Result Schema

\`\`\`json
{
  "schemaVersion": 2,
  "taskId": "task_xxx",
  "provider": "claude-code",
  "completedAt": "2026-01-01T00:00:00.000Z",
  "translations": [
    {
      "id": "1",
      "translatedText": "..."
    },
    {
      "id": "2",
      "translatedText": "..."
    }
  ]
}
\`\`\`

## Quality Checklist

Before submitting results, verify:
- [ ] Every \`id\` in the task file has a corresponding translation
- [ ] All glossary terms are applied consistently
- [ ] All inline code spans are preserved exactly
- [ ] No extra content added, no content omitted
- [ ] Formatting (lists, links, emphasis) is preserved

## Glossary Format

\`.documirror/glossary.json\`:

\`\`\`json
[
  { "source": "component", "target": "\\u7ec4\\u4ef6" },
  { "source": "props", "target": "props" },
  { "source": "hook", "target": "Hook" }
]
\`\`\`

Add entries for technical terms that need consistent translation across all pages.
`;
}
