export function createTaskQueuePlaceholder(): string {
  return `# DocuMirror Translation Queue

This file is generated by DocuMirror.

Run \`documirror translate plan --repo .\` to generate the task queue.
`;
}
