export function createTaskGuide(): string {
  return `# DocuMirror Translation Tasks

This folder contains translation task files generated by DocuMirror.

Workflow:
1. Read JSON files from .documirror/tasks/pending/
2. Translate each item.sourceText into the requested target language
3. Preserve placeholders, inline markup, and list numbering
4. Write result files into .documirror/tasks/done/

Result schema:
{
  "schemaVersion": 1,
  "taskId": "task_xxx",
  "provider": "claude-code",
  "completedAt": "2026-01-01T00:00:00.000Z",
  "items": [
    {
      "segmentId": "...",
      "sourceHash": "...",
      "translatedText": "..."
    }
  ]
}
`;
}
