export function createTaskQueuePlaceholder(): string {
  return `# DocuMirror Translation Queue

This file is generated by DocuMirror.

Run \`documirror translate plan\` to generate tasks, then \`documirror translate run\` to translate them automatically.
`;
}
