export function createTaskQueuePlaceholder(): string {
  return `# DocuMirror Translation Queue

This file is generated by DocuMirror.

Run \`documirror translate plan --repo .\` to generate tasks, then \`documirror translate run --repo .\` to translate them automatically.
`;
}
