export function createTaskGuide(): string {
  return `# DocuMirror Translation Tasks

This folder contains translation task files generated by DocuMirror.

Workflow:
1. Read JSON files from .documirror/tasks/pending/
2. Read each page task in order and translate every content item by its short id; some items may include unchanged neighboring text so inline-code sentences stay coherent
3. Preserve inline code wrapped in backticks, inline markup, and list numbering
4. Write result files into .documirror/tasks/done/

Result schema:
{
  "schemaVersion": 2,
  "taskId": "task_xxx",
  "provider": "claude-code",
  "completedAt": "2026-01-01T00:00:00.000Z",
  "translations": [
    {
      "id": "1",
      "translatedText": "..."
    }
  ]
}
`;
}
