import type {
  TranslationTaskManifest,
  TranslationTaskManifestEntry,
} from "@documirror/shared";
import { translationTaskManifestEntrySchema } from "@documirror/shared";

const TASK_STATUS_ORDER = {
  pending: 0,
  done: 1,
  applied: 2,
  invalid: 3,
} as const;

export function createTaskManifestSummary(
  tasks: TranslationTaskManifestEntry[],
): TranslationTaskManifest["summary"] {
  const summary = {
    total: tasks.length,
    pending: 0,
    done: 0,
    applied: 0,
    invalid: 0,
  };

  tasks.forEach((task) => {
    if (task.status === "pending") {
      summary.pending += 1;
      return;
    }
    if (task.status === "done") {
      summary.done += 1;
      return;
    }
    if (task.status === "applied") {
      summary.applied += 1;
      return;
    }

    summary.invalid += 1;
  });

  return summary;
}

export function renderTaskQueueBoard(
  manifest: TranslationTaskManifest,
): string {
  const lines = [
    "# DocuMirror Translation Queue",
    "",
    "This file is generated by DocuMirror. Do not edit it by hand.",
    "",
    `Generated: ${manifest.generatedAt}`,
    `Summary: total ${manifest.summary.total}, pending ${manifest.summary.pending}, done ${manifest.summary.done}, applied ${manifest.summary.applied}, invalid ${manifest.summary.invalid}`,
    "",
    "Run automatic translation with `documirror translate run --repo .`.",
    "",
    "## Tasks",
  ];

  if (manifest.tasks.length === 0) {
    lines.push("", "- [x] No translation tasks are currently queued.");
    return `${lines.join("\n")}\n`;
  }

  manifest.tasks.forEach((task) => {
    const checkbox =
      task.status === "done" || task.status === "applied" ? "[x]" : "[ ]";
    const title = task.page.title ? ` | ${task.page.title}` : "";
    const verify =
      task.lastVerifyStatus === undefined
        ? ""
        : ` | verify ${task.lastVerifyStatus}${
            task.lastVerifyErrorCount && task.lastVerifyErrorCount > 0
              ? ` (${task.lastVerifyErrorCount} errors)`
              : ""
          }`;
    const run =
      task.lastRunStatus === "fail" && task.lastRunError
        ? ` | last run failed: ${task.lastRunError}`
        : "";
    lines.push(
      `- ${checkbox} ${task.taskId} | ${task.status} | ${task.contentCount} items${title} | ${task.page.url}${verify}${run}`,
    );
  });

  return `${lines.join("\n")}\n`;
}

export function buildInvalidManifestEntry(options: {
  taskId: string;
  taskFile: string;
  doneResultFile?: string;
  page?: TranslationTaskManifestEntry["page"];
  contentCount?: number;
  previousEntry?: TranslationTaskManifestEntry;
}): TranslationTaskManifestEntry {
  const {
    taskId,
    taskFile,
    doneResultFile,
    page,
    contentCount,
    previousEntry,
  } = options;

  return translationTaskManifestEntrySchema.parse({
    taskId,
    page: page ?? previousEntry?.page ?? { url: "" },
    status: "invalid",
    contentCount: contentCount ?? previousEntry?.contentCount ?? 0,
    taskFile: taskFile || previousEntry?.taskFile || "",
    doneResultFile: doneResultFile ?? previousEntry?.doneResultFile,
    completedAt: previousEntry?.completedAt,
    provider: previousEntry?.provider,
    model: previousEntry?.model,
    lastVerifiedAt: previousEntry?.lastVerifiedAt,
    lastVerifyStatus: previousEntry?.lastVerifyStatus,
    lastVerifyErrorCount: previousEntry?.lastVerifyErrorCount,
    lastRunAt: previousEntry?.lastRunAt,
    lastRunStatus: previousEntry?.lastRunStatus,
    lastRunError: previousEntry?.lastRunError,
  });
}

export function compareManifestEntries(
  left: TranslationTaskManifestEntry,
  right: TranslationTaskManifestEntry,
): number {
  const statusDiff =
    TASK_STATUS_ORDER[left.status] - TASK_STATUS_ORDER[right.status];
  if (statusDiff !== 0) {
    return statusDiff;
  }

  const pageDiff = left.page.url.localeCompare(right.page.url);
  if (pageDiff !== 0) {
    return pageDiff;
  }

  return left.taskId.localeCompare(right.taskId);
}
